### ISSUE TITLE
Failure on run test

### ISSUE THREAD

**Issue by garrensmith** [pouchdb/pouchdb-plugin-helper#12]
I'm trying to upgrade the pouchdb-auth module. I've changed all `pouchdb/extras/promise` to `pouchdb-promise`. But now when I run those tests I get this error;

```
 pouchdb-plugin-helper "test"

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/garren/dev/pouchdb-auth/node_modules/pouchdb-plugin-helper/node_modules/.bin/eslint ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:142:18)
    at node.js:939:3
```

Not quite sure how to fix it.

**Comment by garrensmith** [comment]
I've fixed this in latest master
